# Generated by Django 5.0.1 on 2024-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="home_card_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "card_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "card_pdate",
                    models.IntegerField(default=None, max_length=30, null=True),
                ),
                (
                    "card_desc",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "card_image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="homecard1/"
                    ),
                ),
            ],
        ),
    ]
