# Generated by Django 5.0.1 on 2024-02-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home_card_1",
            name="card_pdate",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
