# Generated by Django 5.0.1 on 2024-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_card", "0002_alter_home_card_1_card_pdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="home_card_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "card_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("card_pdate", models.IntegerField(default=None, null=True)),
                (
                    "card_desc",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "card_image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="homecard1/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="home_card_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "card_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("card_pdate", models.IntegerField(default=None, null=True)),
                (
                    "card_desc",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "card_image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="homecard1/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="home_card_4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "card_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("card_pdate", models.IntegerField(default=None, null=True)),
                (
                    "card_desc",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "card_image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="homecard1/"
                    ),
                ),
            ],
        ),
    ]
