# Generated by Django 5.0.1 on 2024-03-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_card", "0004_home_card_1_card_lng_home_card_2_card_lng_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home_card_1",
            name="card_author",
        ),
        migrations.RemoveField(
            model_name="home_card_1",
            name="card_lng",
        ),
        migrations.RemoveField(
            model_name="home_card_1",
            name="card_pdate",
        ),
        migrations.RemoveField(
            model_name="home_card_1",
            name="card_title",
        ),
        migrations.RemoveField(
            model_name="home_card_2",
            name="card_author",
        ),
        migrations.RemoveField(
            model_name="home_card_2",
            name="card_lng",
        ),
        migrations.RemoveField(
            model_name="home_card_2",
            name="card_pdate",
        ),
        migrations.RemoveField(
            model_name="home_card_2",
            name="card_title",
        ),
        migrations.RemoveField(
            model_name="home_card_3",
            name="card_author",
        ),
        migrations.RemoveField(
            model_name="home_card_3",
            name="card_lng",
        ),
        migrations.RemoveField(
            model_name="home_card_3",
            name="card_pdate",
        ),
        migrations.RemoveField(
            model_name="home_card_3",
            name="card_title",
        ),
        migrations.RemoveField(
            model_name="home_card_4",
            name="card_author",
        ),
        migrations.RemoveField(
            model_name="home_card_4",
            name="card_lng",
        ),
        migrations.RemoveField(
            model_name="home_card_4",
            name="card_pdate",
        ),
        migrations.RemoveField(
            model_name="home_card_4",
            name="card_title",
        ),
        migrations.AlterField(
            model_name="home_card_1",
            name="card_desc",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="home_card_2",
            name="card_desc",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="home_card_3",
            name="card_desc",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="home_card_4",
            name="card_desc",
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
