# Generated by Django 5.0.1 on 2024-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="news_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "video_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("video_pdate", models.IntegerField(default=None, null=True)),
                (
                    "video_desc",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "video_img_preview",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_img_show",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(default=None, null=True, upload_to="news_video/"),
                ),
            ],
        ),
    ]
