# Generated by Django 5.0.1 on 2024-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_video",
            name="video_lng",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
