# Generated by Django 5.0.1 on 2024-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_videos", "0002_news_video_video_lng"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("video_lng", models.CharField(default=None, max_length=30, null=True)),
                (
                    "video_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("video_pdate", models.IntegerField(default=None, null=True)),
                (
                    "video_desc",
                    models.CharField(default=None, max_length=150, null=True),
                ),
                (
                    "video_img_preview",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_img_show",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(default=None, null=True, upload_to="news_video/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sports_video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_title",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("video_lng", models.CharField(default=None, max_length=30, null=True)),
                (
                    "video_author",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                ("video_pdate", models.IntegerField(default=None, null=True)),
                (
                    "video_desc",
                    models.CharField(default=None, max_length=150, null=True),
                ),
                (
                    "video_img_preview",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_img_show",
                    models.ImageField(
                        default=None, null=True, upload_to="news_video_image/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(default=None, null=True, upload_to="news_video/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="news_video",
            name="video_desc",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
