# Generated by Django 5.0.1 on 2024-02-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marque_feature", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marquee_feature_1",
            name="des",
            field=models.CharField(default="", max_length=30),
        ),
    ]
