# Generated by Django 5.0.1 on 2024-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marque_feature", "0002_marquee_feature_1_des"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marquee_feature_1",
            name="des",
        ),
        migrations.RemoveField(
            model_name="marquee_feature_1",
            name="name",
        ),
        migrations.AddField(
            model_name="marquee_feature_1",
            name="book_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="book_image/"
            ),
        ),
    ]
