# Generated by Django 5.0.1 on 2024-02-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marque_feature", "0003_remove_marquee_feature_1_des_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marquee_feature_1",
            name="book_image",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="book_image/"
            ),
        ),
    ]
