# Generated by Django 5.0.1 on 2024-02-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marque_feature", "0004_alter_marquee_feature_1_book_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="marquee_feature_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "magazines_image",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="book_image/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="marquee_feature_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_image_2",
                    models.ImageField(
                        default=None, max_length=250, null=True, upload_to="book_image/"
                    ),
                ),
            ],
        ),
    ]
