# Generated by Django 5.0.1 on 2024-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marque_feature", "0005_marquee_feature_2_marquee_feature_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marquee_feature_2",
            name="magazines_image",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="magazines_image/"
            ),
        ),
        migrations.AlterField(
            model_name="marquee_feature_3",
            name="book_image_2",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="book_image_2/"
            ),
        ),
    ]
