# Generated by Django 5.0.1 on 2024-03-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "S_image",
                    models.ImageField(default=None, max_length=500, upload_to="search"),
                ),
                ("s_title", models.CharField(default=None, max_length=30, null=True)),
                ("s_lng", models.CharField(default=None, max_length=30, null=True)),
                ("s_author", models.CharField(default=None, max_length=30, null=True)),
                ("s_pdate", models.IntegerField(default=None, null=True)),
                ("s_desc", models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
