# Generated by Django 5.0.1 on 2024-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_post_comments_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="posts/"
            ),
        ),
    ]
