# Generated by Django 5.0.1 on 2024-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_comment_post_story"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="storyfile",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                upload_to="stories/",
            ),
        ),
    ]
