# Generated by Django 5.0.1 on 2024-03-22 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_comment_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventtitle", models.TextField(blank=True, default=None, null=True)),
                ("eventcat", models.TextField(blank=True, default=None, null=True)),
                ("eventdesc", models.TextField(blank=True, default=None, null=True)),
                ("eventdmonth", models.TextField(blank=True, default=None, null=True)),
                ("eventdday", models.TextField(blank=True, default=None, null=True)),
                ("eventdyear", models.TextField(blank=True, default=None, null=True)),
                ("eventfhr", models.TextField(blank=True, default=None, null=True)),
                ("eventfmin", models.TextField(blank=True, default=None, null=True)),
                ("eventfampm", models.TextField(blank=True, default=None, null=True)),
                ("eventthr", models.TextField(blank=True, default=None, null=True)),
                ("eventtmin", models.TextField(blank=True, default=None, null=True)),
                ("eventtampm", models.TextField(blank=True, default=None, null=True)),
                (
                    "eventfr_every",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "eventfr_basis",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("eventfr_till", models.TextField(blank=True, default=None, null=True)),
                ("eventaddress", models.TextField(blank=True, default=None, null=True)),
                ("event_guest", models.TextField(blank=True, default=None, null=True)),
                ("event_fee", models.TextField(blank=True, default=None, null=True)),
                ("event_req", models.TextField(blank=True, default=None, null=True)),
                (
                    "eventimg",
                    models.FileField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        upload_to="stories/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
