# Generated by Django 5.0.1 on 2024-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_events"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="eventaddress",
            new_name="eventaddressp",
        ),
        migrations.AddField(
            model_name="events",
            name="eventaddressv",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
